
CREATE TABLE [dbo].[d_Competition](
	[CompetitionID] [int] NOT NULL,
	[CompetitionDistance] [int] NOT NULL,
	[OpenSinceMonthYear] [varchar](50) NULL,
 CONSTRAINT [PK_COMPETITION] PRIMARY KEY CLUSTERED
(
	[CompetitionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[d_Date](
	[DateID] [int] NOT NULL,
	[Day] [int] NOT NULL,
	[Month] [int] NOT NULL,
	[Year] [int] NOT NULL,
	[Week] [int] NOT NULL,
	[Quarter] [int] NOT NULL,
	[DayOfWeek] [int] NOT NULL,
 CONSTRAINT [PK_DATE] PRIMARY KEY CLUSTERED
(
	[DateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[d_Open](
	[OpenID] [int] NOT NULL,
	[IsOpen] [binary](1) NOT NULL,
 CONSTRAINT [PK_d_Open] PRIMARY KEY CLUSTERED
(
	[OpenID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[d_Promotion](
	[PromotionID] [int] NOT NULL,
	[IsActive] [binary](1) NOT NULL,
 CONSTRAINT [PK_d_Promotion] PRIMARY KEY CLUSTERED
(
	[PromotionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[d_Promotion2](
	[Promotion2ID] [int] NOT NULL,
	[IsPromotion] [binary](1) NOT NULL,
	[SinceWeekYear] [varchar](50) NULL,
	[Interval] [varchar](50) NULL,
 CONSTRAINT [PK_PROMOTION2] PRIMARY KEY CLUSTERED
(
	[Promotion2ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[d_SchoolHoliday](
	[SchoolHolidayID] [int] NOT NULL,
	[IsSchoolHoliday] [binary](1) NOT NULL,
 CONSTRAINT [PK_d_SchoolHoliday] PRIMARY KEY CLUSTERED
(
	[SchoolHolidayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[d_Store](
	[StoreID] [int] NOT NULL,
	[Promotion2ID] [int] NOT NULL,
	[CompetitionID] [int] NULL,
	[StoreType] [varchar](1) NOT NULL,
	[Assortment] [varchar](1) NOT NULL,
	[StoreNr] [int] NOT NULL,
 CONSTRAINT [PK_STORE] PRIMARY KEY CLUSTERED
(
	[StoreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ__Store__CE2A3D8CCA889AFE] UNIQUE NONCLUSTERED
(
	[Promotion2ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[d_Store]  WITH CHECK ADD  CONSTRAINT [Store_fk0] FOREIGN KEY([Promotion2ID])
REFERENCES [dbo].[d_Promotion2] ([Promotion2ID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[d_Store] CHECK CONSTRAINT [Store_fk0]
GO

ALTER TABLE [dbo].[d_Store]  WITH CHECK ADD  CONSTRAINT [Store_fk1] FOREIGN KEY([CompetitionID])
REFERENCES [dbo].[d_Competition] ([CompetitionID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[d_Store] CHECK CONSTRAINT [Store_fk1]
GO


CREATE TABLE [dbo].[f_StoreSales](
	[StoreID] [int] NOT NULL,
	[DateID] [int] NOT NULL,
	[OpenID] [int] NOT NULL,
	[PromotionID] [int] NOT NULL,
	[SchoolHolidayID] [int] NOT NULL,
	[Sales] [int] NOT NULL,
	[Customers] [int] NOT NULL,
 CONSTRAINT [PK_STORESALES] PRIMARY KEY CLUSTERED
(
	[StoreID] ASC,
	[DateID] ASC,
	[OpenID] ASC,
	[PromotionID] ASC,
	[SchoolHolidayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[f_StoreSales]  WITH CHECK ADD  CONSTRAINT [StoreSales_fk0] FOREIGN KEY([StoreID])
REFERENCES [dbo].[d_Store] ([StoreID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[f_StoreSales] CHECK CONSTRAINT [StoreSales_fk0]
GO

ALTER TABLE [dbo].[f_StoreSales]  WITH CHECK ADD  CONSTRAINT [StoreSales_fk1] FOREIGN KEY([DateID])
REFERENCES [dbo].[d_Date] ([DateID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[f_StoreSales] CHECK CONSTRAINT [StoreSales_fk1]
GO

ALTER TABLE [dbo].[f_StoreSales]  WITH CHECK ADD  CONSTRAINT [StoreSales_fk2] FOREIGN KEY([OpenID])
REFERENCES [dbo].[d_Open] ([OpenID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[f_StoreSales] CHECK CONSTRAINT [StoreSales_fk2]
GO

ALTER TABLE [dbo].[f_StoreSales]  WITH CHECK ADD  CONSTRAINT [StoreSales_fk3] FOREIGN KEY([SchoolHolidayID])
REFERENCES [dbo].[d_SchoolHoliday] ([SchoolHolidayID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[f_StoreSales] CHECK CONSTRAINT [StoreSales_fk3]
GO

ALTER TABLE [dbo].[f_StoreSales]  WITH CHECK ADD  CONSTRAINT [StoreSales_fk4] FOREIGN KEY([PromotionID])
REFERENCES [dbo].[d_Promotion] ([PromotionID])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[f_StoreSales] CHECK CONSTRAINT [StoreSales_fk4]
GO
